# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Info_Dialog(object):
    def setupUi(self,dialog,data):
        dialog.setObjectName("Dialog")
        dialog.resize(764, 865)
        dialog.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_15 = QtWidgets.QWidget(dialog)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 30))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_20.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    font-size:16px;\n"
"    font-weight:400;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 #777777,stop:1 #000000);\n"
"    color:white;\n"
"  }")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.verticalLayout.addWidget(self.widget_15)
        self.widget = QtWidgets.QWidget(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 740))
        self.widget.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(720, 480))
        self.label.setMaximumSize(QtCore.QSize(16777215, 480))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(dialog)
        self.widget_2.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"    background:#444444;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 5, 0, 5)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"    background:#444444;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_number = QtWidgets.QLabel(self.widget_4)
        self.label_number.setObjectName("label_number")
        self.horizontalLayout.addWidget(self.label_number)
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_frameTime = QtWidgets.QLabel(self.widget_7)
        self.label_frameTime.setObjectName("label_frameTime")
        self.horizontalLayout_4.addWidget(self.label_frameTime)
        self.gridLayout.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_id = QtWidgets.QLabel(self.widget_5)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout_2.addWidget(self.label_id)
        self.gridLayout.addWidget(self.widget_5, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_cameraSite = QtWidgets.QLabel(self.widget_6)
        self.label_cameraSite.setObjectName("label_cameraSite")
        self.horizontalLayout_3.addWidget(self.label_cameraSite)
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.gridLayout.addWidget(self.widget_8, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.widget_10)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_20cm = QtWidgets.QLabel(self.widget_10)
        self.label_20cm.setObjectName("label_20cm")
        self.horizontalLayout_6.addWidget(self.label_20cm)
        self.verticalLayout_3.addWidget(self.widget_10, 0, QtCore.Qt.AlignHCenter)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_10cm = QtWidgets.QLabel(self.widget_11)
        self.label_10cm.setObjectName("label_10cm")
        self.horizontalLayout_7.addWidget(self.label_10cm)
        self.verticalLayout_3.addWidget(self.widget_11, 0, QtCore.Qt.AlignHCenter)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.widget_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_5cm = QtWidgets.QLabel(self.widget_12)
        self.label_5cm.setObjectName("label_5cm")
        self.horizontalLayout_8.addWidget(self.label_5cm)
        self.verticalLayout_3.addWidget(self.widget_12, 0, QtCore.Qt.AlignHCenter)
        self.widget_13 = QtWidgets.QWidget(self.widget_9)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.widget_13)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.label_2cm = QtWidgets.QLabel(self.widget_13)
        self.label_2cm.setObjectName("label_2cm")
        self.horizontalLayout_9.addWidget(self.label_2cm)
        self.verticalLayout_3.addWidget(self.widget_13, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_14 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_10.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prev_Button = QtWidgets.QPushButton(self.widget_14)
        self.prev_Button.setStyleSheet("QPushButton{\n"
"           border:none;\n"
"          background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(96,157,200),stop:1 rgb(0,94,150));\n"
"          font-size:15px;\n"
"            color:white;\n"
"            width:120px;\n"
"            height:40px;\n"
"            text-align:center;\n"
"            border-radius:5px;\n"
"        }")
        self.prev_Button.setObjectName("prev_Button")
        self.horizontalLayout_10.addWidget(self.prev_Button)
        self.next_Button = QtWidgets.QPushButton(self.widget_14)
        self.next_Button.setStyleSheet("QPushButton{\n"
"           border:none;\n"
"          background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(96,157,200),stop:1 rgb(0,94,150));\n"
"          font-size:15px;\n"
"            color:white;\n"
"            width:120px;\n"
"            height:40px;\n"
"            text-align:center;\n"
"            border-radius:5px;\n"
"        }")
        self.next_Button.setObjectName("next_Button")
        self.horizontalLayout_10.addWidget(self.next_Button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.close_Button = QtWidgets.QPushButton(self.widget_14)
        self.close_Button.setStyleSheet("QPushButton{\n"
"           border:none;\n"
"          background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(96,157,200),stop:1 rgb(0,94,150));\n"
"          font-size:15px;\n"
"            color:white;\n"
"            width:120px;\n"
"            height:40px;\n"
"            text-align:center;\n"
"            border-radius:5px;\n"
"        }")
        self.close_Button.setObjectName("close_Button")
        self.horizontalLayout_10.addWidget(self.close_Button)
        self.verticalLayout_2.addWidget(self.widget_14)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(dialog,data)
        self.close_Button.clicked.connect(dialog.exec)
        QtCore.QMetaObject.connectSlotsByName(dialog)


    def retranslateUi(self, Dialog,data):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "InfoDialog"))
        self.label_20.setText(_translate("Dialog", "  分割信息"))
        self.label_2.setText(_translate("Dialog", "编号："))
        self.label_number.setText(_translate("Dialog", str(data[0])))
        self.label_8.setText(_translate("Dialog", "图片帧时间："))
        self.label_frameTime.setText(_translate("Dialog", str(data[3])))
        self.label_4.setText(_translate("Dialog", "摄像头ID："))
        self.label_id.setText(_translate("Dialog", str(data[1])))
        self.label_6.setText(_translate("Dialog", "摄像头点位："))
        self.label_cameraSite.setText(_translate("Dialog", str(data[2])))
        self.label_11.setText(_translate("Dialog", "矿石尺寸占比："))
        self.label_12.setText(_translate("Dialog", "(1)20+:"))
        self.label_20cm.setText(_translate("Dialog", str(data[4])))
        self.label_14.setText(_translate("Dialog", "(2)10+:"))
        self.label_10cm.setText(_translate("Dialog", str(data[5])))
        self.label_16.setText(_translate("Dialog", "(3) 5+:"))
        self.label_5cm.setText(_translate("Dialog", str(data[6])))
        self.label_18.setText(_translate("Dialog", "(4) 2+:"))
        self.label_2cm.setText(_translate("Dialog", str(data[7])))
        self.prev_Button.setText(_translate("Dialog", "上一条"))
        self.next_Button.setText(_translate("Dialog", "下一条"))
        self.close_Button.setText(_translate("Dialog", "确定"))

if __name__ == '__main__':
    import  sys
    from ResultTableView import DataGrid
    from PyQt5.QtWidgets import*


    def test(index):
            data = example.getRowData(index.row())
            dialog=QDialog()
            content=Info_Dialog()
            content.setupUi(dialog,data)
            dialog.exec_()

    app = QApplication(sys.argv)
    example = DataGrid()
    example.tableView.doubleClicked.connect(test)




    # 创建窗口

    # 显示窗口

    example.show()

    sys.exit(app.exec_())