# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Video1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWidget1(object):
    def setupUi(self, VideoWidget1):
        VideoWidget1.setObjectName("VideoWidget1")
        VideoWidget1.resize(759, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoWidget1.sizePolicy().hasHeightForWidth())
        VideoWidget1.setSizePolicy(sizePolicy)
        VideoWidget1.setMinimumSize(QtCore.QSize(0, 400))
        VideoWidget1.setStyleSheet("QWidget{\n"
" background:#FFFFFF;}")
        self.gridLayout = QtWidgets.QGridLayout(VideoWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetView = QtWidgets.QWidget(VideoWidget1)
        self.widgetView.setObjectName("widgetView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_0 = QtWidgets.QLabel(self.widgetView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setMaximumSize(QtCore.QSize(720, 480))
        self.label_0.setStyleSheet("")
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")
        self.gridLayout_2.addWidget(self.label_0, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widgetView, 0, 0, 1, 1)

        self.retranslateUi(VideoWidget1)
        QtCore.QMetaObject.connectSlotsByName(VideoWidget1)

    def retranslateUi(self, VideoWidget1):
        _translate = QtCore.QCoreApplication.translate
        VideoWidget1.setWindowTitle(_translate("VideoWidget1", "Form"))
