# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SumDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from SumAllTable import DataGridAll

class Sum_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1214, 675)
        Dialog.setStyleSheet("background-color:#555555\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_20 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 30))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_20.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    font-size:16px;\n"
"    font-weight:400;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 #777777,stop:1 #000000);\n"
"    color:white;\n"
"  }")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 740))
        self.widget.setStyleSheet("background-color:#444444")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"    background:#444444;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_2.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(40, 20, 381, 41))
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 72, 15))
        self.label_2.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setGeometry(QtCore.QRect(170, 10, 161, 22))
        self.comboBox.setStyleSheet("background-color:#444444;")
        self.comboBox.setObjectName("comboBox")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(40, 70, 381, 41))
        self.widget_4.setObjectName("widget_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_3.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 10, 161, 22))
        self.comboBox_2.setStyleSheet("background-color:#444444;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(170, 180, 93, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"           border:none;\n"
"          background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(96,157,200),stop:1 rgb(0,94,150));\n"
"          font-size:15px;\n"
"            color:white;\n"
"            width:120px;\n"
"            height:40px;\n"
"            text-align:center;\n"
"            border-radius:5px;\n"
"        }\n"
"QPushButton:hover{\n"
"            color:#0caaff\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(50, 88, 138)\n"
"}\n"
"QPushButton:disabled{\n"
"color:rgb(172, 172, 172);\n"
"background-color:rgb(93, 93, 93)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(720, 0))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 740))
        self.widget_11.setStyleSheet("background-color:#444444")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_63 = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(0, 30))
        self.label_63.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_63.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"   color:white;\n"
"    background:#444444;\n"
"}")
        self.label_63.setObjectName("label_63")
        self.gridLayout_8.addWidget(self.label_63, 0, 0, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 480))
        self.widget_15.setStyleSheet("QWidget{\n"
"background-color:#555555\n"
"}\n"
"QPushButton{\n"
"           border:none;\n"
"          background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(96,157,200),stop:1 rgb(0,94,150));\n"
"          font-size:15px;\n"
"            color:white;\n"
"            width:120px;\n"
"            height:40px;\n"
"            text-align:center;\n"
"            border-radius:5px;\n"
"        }\n"
"QPushButton:hover{\n"
"            color:#0caaff\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(50, 88, 138)\n"
"}\n"
"QPushButton:disabled{\n"
"color:rgb(172, 172, 172);\n"
"background-color:rgb(93, 93, 93)\n"
"}\n"
"\n"
"QLable{\n"
"color:white;\n"
"background:#222222;\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.datagridall=DataGridAll()
        self.verticalLayout.addWidget(self.datagridall)
        self.gridLayout_8.addWidget(self.widget_15, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_11, 1, 1, 2, 1)
        self.widget_5 = QtWidgets.QWidget(Dialog)
        self.widget_5.setStyleSheet("background-color:#444444")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_5)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color:#666666;\n"
"}\n"
"QTabWidget::pane{\n"
"\n"
"border-top: 1px solid;\n"
"\n"
"border-color: #333333;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"min-width:80px;\n"
"min-height:30px;\n"
"color: white;\n"
"background:#666666;\n"
"\n"
"border: 0px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"min-width:85px;\n"
"min-height:30px;\n"
"color: white;\n"
"background:#009DE2;\n"
"border: 0px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtWidgets.QWidget(self.tab)
        self.widget_6.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_6)
        self.label_8.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_6)
        self.label_13.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_6)
        self.label_11.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        self.label_10.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_6)
        self.label_9.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_7 = QtWidgets.QWidget(self.tab_2)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 431, 171))
        self.widget_7.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.widget_7)
        self.label_15.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_7)
        self.label_16.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_7)
        self.label_17.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_7)
        self.label_18.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_7)
        self.label_19.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_7)
        self.label_21.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_7)
        self.label_22.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_7)
        self.label_23.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_7)
        self.label_24.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_7)
        self.label_25.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_7)
        self.label_26.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_8 = QtWidgets.QWidget(self.tab_5)
        self.widget_8.setGeometry(QtCore.QRect(10, 10, 431, 171))
        self.widget_8.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_27 = QtWidgets.QLabel(self.widget_8)
        self.label_27.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_8)
        self.label_28.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_8)
        self.label_29.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_8)
        self.label_30.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_8)
        self.label_31.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_8)
        self.label_32.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_8)
        self.label_33.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 3, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_8)
        self.label_34.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 4, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_8)
        self.label_35.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 4, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget_8)
        self.label_36.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 5, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget_8)
        self.label_37.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_9 = QtWidgets.QWidget(self.tab_6)
        self.widget_9.setGeometry(QtCore.QRect(10, 10, 431, 171))
        self.widget_9.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_38 = QtWidgets.QLabel(self.widget_9)
        self.label_38.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.widget_9)
        self.label_39.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.widget_9)
        self.label_40.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.widget_9)
        self.label_41.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_9)
        self.label_42.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget_9)
        self.label_43.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_9)
        self.label_44.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 3, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget_9)
        self.label_45.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 4, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.widget_9)
        self.label_46.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 4, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.widget_9)
        self.label_47.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 5, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.widget_9)
        self.label_48.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget_10 = QtWidgets.QWidget(self.tab_7)
        self.widget_10.setGeometry(QtCore.QRect(10, 10, 431, 171))
        self.widget_10.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_49 = QtWidgets.QLabel(self.widget_10)
        self.label_49.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget_10)
        self.label_50.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_10)
        self.label_51.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.widget_10)
        self.label_52.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.widget_10)
        self.label_53.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 2, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.widget_10)
        self.label_54.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 3, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.widget_10)
        self.label_55.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.widget_10)
        self.label_56.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 4, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.widget_10)
        self.label_57.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 4, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.widget_10)
        self.label_58.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 5, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.widget_10)
        self.label_59.setStyleSheet("QLabel {\n"
"   color:white;\n"
"}")
        self.label_59.setObjectName("label_59")
        self.gridLayout_6.addWidget(self.label_59, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_2.addWidget(self.widget_5, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_20.setText(_translate("Dialog", "  分割统计"))
        self.label.setText(_translate("Dialog", "统计设置"))
        self.label_2.setText(_translate("Dialog", "摄像头ID:"))
        self.label_3.setText(_translate("Dialog", "摄像头点位:"))
        self.pushButton.setText(_translate("Dialog", "统计"))
        self.label_63.setText(_translate("Dialog", "统计设置"))
        self.label_5.setText(_translate("Dialog", "(1)20+:"))
        self.label_14.setText(_translate("Dialog", "%"))
        self.label_12.setText(_translate("Dialog", "%"))
        self.label_8.setText(_translate("Dialog", "(4)2+:"))
        self.label_13.setText(_translate("Dialog", "%"))
        self.label_11.setText(_translate("Dialog", "%"))
        self.label_7.setText(_translate("Dialog", "(3)5+:"))
        self.label_10.setText(_translate("Dialog", "%"))
        self.label_4.setText(_translate("Dialog", "平均矿石尺寸占比："))
        self.label_6.setText(_translate("Dialog", "(2)10+:"))
        self.label_9.setText(_translate("Dialog", "(5)平均尺寸："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "1分钟"))
        self.label_15.setText(_translate("Dialog", "平均矿石尺寸占比："))
        self.label_16.setText(_translate("Dialog", "(1)20+:"))
        self.label_17.setText(_translate("Dialog", "%"))
        self.label_18.setText(_translate("Dialog", "(2)10+:"))
        self.label_19.setText(_translate("Dialog", "%"))
        self.label_21.setText(_translate("Dialog", "(3)5+:"))
        self.label_22.setText(_translate("Dialog", "%"))
        self.label_23.setText(_translate("Dialog", "(4)2+:"))
        self.label_24.setText(_translate("Dialog", "%"))
        self.label_25.setText(_translate("Dialog", "(5)平均尺寸："))
        self.label_26.setText(_translate("Dialog", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "5分钟"))
        self.label_27.setText(_translate("Dialog", "平均矿石尺寸占比："))
        self.label_28.setText(_translate("Dialog", "(1)20+:"))
        self.label_29.setText(_translate("Dialog", "%"))
        self.label_30.setText(_translate("Dialog", "(2)10+:"))
        self.label_31.setText(_translate("Dialog", "%"))
        self.label_32.setText(_translate("Dialog", "(3)5+:"))
        self.label_33.setText(_translate("Dialog", "%"))
        self.label_34.setText(_translate("Dialog", "(4)2+:"))
        self.label_35.setText(_translate("Dialog", "%"))
        self.label_36.setText(_translate("Dialog", "(5)平均尺寸："))
        self.label_37.setText(_translate("Dialog", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "10分钟"))
        self.label_38.setText(_translate("Dialog", "平均矿石尺寸占比："))
        self.label_39.setText(_translate("Dialog", "(1)20+:"))
        self.label_40.setText(_translate("Dialog", "%"))
        self.label_41.setText(_translate("Dialog", "(2)10+:"))
        self.label_42.setText(_translate("Dialog", "%"))
        self.label_43.setText(_translate("Dialog", "(3)5+:"))
        self.label_44.setText(_translate("Dialog", "%"))
        self.label_45.setText(_translate("Dialog", "(4)2+:"))
        self.label_46.setText(_translate("Dialog", "%"))
        self.label_47.setText(_translate("Dialog", "(5)平均尺寸："))
        self.label_48.setText(_translate("Dialog", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "15分钟"))
        self.label_49.setText(_translate("Dialog", "平均矿石尺寸占比："))
        self.label_50.setText(_translate("Dialog", "(1)20+:"))
        self.label_51.setText(_translate("Dialog", "%"))
        self.label_52.setText(_translate("Dialog", "(2)10+:"))
        self.label_53.setText(_translate("Dialog", "%"))
        self.label_54.setText(_translate("Dialog", "(3)5+:"))
        self.label_55.setText(_translate("Dialog", "%"))
        self.label_56.setText(_translate("Dialog", "(4)2+:"))
        self.label_57.setText(_translate("Dialog", "%"))
        self.label_58.setText(_translate("Dialog", "(5)平均尺寸："))
        self.label_59.setText(_translate("Dialog", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "30分钟"))
